<?php
/**
* Class for the CPTUI importer.
*
* @see https://wordpress.org/plugins/redux-framework/
*
* @package Merlin WP
*/

class Merlin_Elementor_Stylekit_Importer {
    /**
    * Import CPTUI data from a JSON file, generated by the CPTUI plugin.
    *
    * @param array $import_data Array of arrays. Child array contains 'cpt_file_url' and 'tax_file_url'.
    *
    * @return boolean
    */
    public static function import( $import_data ) {
        // CPTUI plugin is not active!
        if ( ! did_action( 'elementor/loaded' ) || empty( $import_data ) ) {
            return false;
        }
        // Update Elementor Default Style Kit
        $local_data = file_get_contents( $import_data );
        $stylekit_data= json_decode( $local_data, true );
        $stylekit = maybe_unserialize( $stylekit_data );
        update_post_meta( 4536, '_elementor_page_settings', $stylekit );

        return true;
    }
}
